# LoadBalancer Service
# Enables the pods in a deployment to be accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: myproject-svc
spec:
  selector:
    app: myproject
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myproject
  labels:
    app: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
    spec:
      # The sqlite3 database is shared through this volume
      # It's not a good approach for production use since it is deleted when the pod goes down
      volumes:
      - name: tmp-database
        emptyDir: {}
      containers:
      - name: myproject
        # I added this
        ports:
          - containerPort: 5000
        image: gcr.io/first-304221/myproject:1
        # image: myproject:1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data
          name: tmp-database
        env:
        - name: DATABASE_DIR
          value: /data
        - name: CELERY_BROKER_URL
          value: "amqp://guest:guest@rabbitmq-service:5672"
        - name: CELERY_RESULT_BACKEND
          value: "rpc://"
#         env:
#         - name: CELERY_BROKER_URL
#           value: 'redis://redis-service:6379/0'
#         - name: CELERY_RESULT_BACKEND
#           value: 'redis://redis-service:6379/1'
      - name: consumer-small
        # image: consumer-small:1
        image: gcr.io/first-304221/consumer-small:1
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data
          name: tmp-database
        env:
        - name: DATABASE_DIR
          value: /data
        - name: CELERY_BROKER_URL
          value: "amqp://guest:guest@rabbitmq-service:5672"
        - name: CELERY_RESULT_BACKEND
          value: "rpc://"
#         env:
#         - name: CELERY_BROKER_URL
#           value: 'redis://redis-service:6379/0'
#         - name: CELERY_RESULT_BACKEND
#           value: 'redis://redis-service:6379/1'
