# Generated by Django 2.0.7 on 2018-07-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('string_a', models.TextField()),
                ('string_b', models.TextField()),
                ('lcs', models.TextField(default=None, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
